// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AcsEvent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AcsEvent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
class AcsEventDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AcsEventData>
     _instance;
} _AcsEventData_default_instance_;

namespace protobuf_AcsEvent_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, messagetype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, probablecause_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, uniqueno_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, stb_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, createtime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, entityinstance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, apptypecode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, messageformat_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, desp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcsEventData, ctrltype_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(AcsEventData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_AcsEventData_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "AcsEvent.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::proto::protobuf_CommonDefine_2eproto::InitDefaults();
  _AcsEventData_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_AcsEventData_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016AcsEvent.proto\022\005proto\032\022CommonDefine.pr"
      "oto\"\336\002\n\014AcsEventData\022\023\n\013messageType\030\001 \001("
      "\t\022\025\n\rprobableCause\030\002 \001(\t\022\020\n\010uniqueNo\030\003 \001"
      "(\t\022\013\n\003stb\030\004 \001(\t\022\022\n\ncreateTime\030\005 \001(\t\022\026\n\016e"
      "ntityInstance\030\006 \001(\t\0226\n\013appTypeCode\030\007 \001(\016"
      "2!.proto.EnumDefineData.AppTypeEnum\022\025\n\rm"
      "essageFormat\030\010 \001(\t\022\017\n\007message\030\t \001(\t\022\014\n\004d"
      "esp\030\n \001(\t\0224\n\010ctrlType\030\013 \001(\0162\".proto.AcsE"
      "ventData.TmCtrlTypeEnum\"3\n\016TmCtrlTypeEnu"
      "m\022\020\n\014STB_HEARTBIT\020\000\022\017\n\013CTRL_TM_RST\020\001B$\n\030"
      "com.fiberhome.fums.protoB\010AcsEventb\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 442);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AcsEvent.proto", &protobuf_RegisterTypes);
  ::proto::protobuf_CommonDefine_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_AcsEvent_2eproto

const ::google::protobuf::EnumDescriptor* AcsEventData_TmCtrlTypeEnum_descriptor() {
  protobuf_AcsEvent_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_AcsEvent_2eproto::file_level_enum_descriptors[0];
}
bool AcsEventData_TmCtrlTypeEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const AcsEventData_TmCtrlTypeEnum AcsEventData::STB_HEARTBIT;
const AcsEventData_TmCtrlTypeEnum AcsEventData::CTRL_TM_RST;
const AcsEventData_TmCtrlTypeEnum AcsEventData::TmCtrlTypeEnum_MIN;
const AcsEventData_TmCtrlTypeEnum AcsEventData::TmCtrlTypeEnum_MAX;
const int AcsEventData::TmCtrlTypeEnum_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AcsEventData::kMessageTypeFieldNumber;
const int AcsEventData::kProbableCauseFieldNumber;
const int AcsEventData::kUniqueNoFieldNumber;
const int AcsEventData::kStbFieldNumber;
const int AcsEventData::kCreateTimeFieldNumber;
const int AcsEventData::kEntityInstanceFieldNumber;
const int AcsEventData::kAppTypeCodeFieldNumber;
const int AcsEventData::kMessageFormatFieldNumber;
const int AcsEventData::kMessageFieldNumber;
const int AcsEventData::kDespFieldNumber;
const int AcsEventData::kCtrlTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AcsEventData::AcsEventData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_AcsEvent_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.AcsEventData)
}
AcsEventData::AcsEventData(const AcsEventData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  messagetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.messagetype().size() > 0) {
    messagetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messagetype_);
  }
  probablecause_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.probablecause().size() > 0) {
    probablecause_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.probablecause_);
  }
  uniqueno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.uniqueno().size() > 0) {
    uniqueno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uniqueno_);
  }
  stb_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stb().size() > 0) {
    stb_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stb_);
  }
  createtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.createtime().size() > 0) {
    createtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.createtime_);
  }
  entityinstance_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.entityinstance().size() > 0) {
    entityinstance_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entityinstance_);
  }
  messageformat_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.messageformat().size() > 0) {
    messageformat_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messageformat_);
  }
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  desp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.desp().size() > 0) {
    desp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.desp_);
  }
  ::memcpy(&apptypecode_, &from.apptypecode_,
    static_cast<size_t>(reinterpret_cast<char*>(&ctrltype_) -
    reinterpret_cast<char*>(&apptypecode_)) + sizeof(ctrltype_));
  // @@protoc_insertion_point(copy_constructor:proto.AcsEventData)
}

void AcsEventData::SharedCtor() {
  messagetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  probablecause_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uniqueno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stb_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  createtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entityinstance_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageformat_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&apptypecode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ctrltype_) -
      reinterpret_cast<char*>(&apptypecode_)) + sizeof(ctrltype_));
  _cached_size_ = 0;
}

AcsEventData::~AcsEventData() {
  // @@protoc_insertion_point(destructor:proto.AcsEventData)
  SharedDtor();
}

void AcsEventData::SharedDtor() {
  messagetype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  probablecause_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uniqueno_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stb_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  createtime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entityinstance_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageformat_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desp_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AcsEventData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AcsEventData::descriptor() {
  protobuf_AcsEvent_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_AcsEvent_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AcsEventData& AcsEventData::default_instance() {
  protobuf_AcsEvent_2eproto::InitDefaults();
  return *internal_default_instance();
}

AcsEventData* AcsEventData::New(::google::protobuf::Arena* arena) const {
  AcsEventData* n = new AcsEventData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AcsEventData::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.AcsEventData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messagetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  probablecause_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uniqueno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stb_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  createtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entityinstance_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageformat_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&apptypecode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ctrltype_) -
      reinterpret_cast<char*>(&apptypecode_)) + sizeof(ctrltype_));
  _internal_metadata_.Clear();
}

bool AcsEventData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.AcsEventData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string messageType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_messagetype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->messagetype().data(), static_cast<int>(this->messagetype().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.messageType"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string probableCause = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_probablecause()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->probablecause().data(), static_cast<int>(this->probablecause().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.probableCause"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string uniqueNo = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uniqueno()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->uniqueno().data(), static_cast<int>(this->uniqueno().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.uniqueNo"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stb = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stb()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stb().data(), static_cast<int>(this->stb().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.stb"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string createTime = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_createtime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->createtime().data(), static_cast<int>(this->createtime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.createTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string entityInstance = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_entityinstance()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->entityinstance().data(), static_cast<int>(this->entityinstance().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.entityInstance"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.EnumDefineData.AppTypeEnum appTypeCode = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_apptypecode(static_cast< ::proto::EnumDefineData_AppTypeEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string messageFormat = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_messageformat()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->messageformat().data(), static_cast<int>(this->messageformat().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.messageFormat"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string desp = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_desp()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->desp().data(), static_cast<int>(this->desp().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.AcsEventData.desp"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.AcsEventData.TmCtrlTypeEnum ctrlType = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ctrltype(static_cast< ::proto::AcsEventData_TmCtrlTypeEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.AcsEventData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.AcsEventData)
  return false;
#undef DO_
}

void AcsEventData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.AcsEventData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string messageType = 1;
  if (this->messagetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messagetype().data(), static_cast<int>(this->messagetype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.messageType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->messagetype(), output);
  }

  // string probableCause = 2;
  if (this->probablecause().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->probablecause().data(), static_cast<int>(this->probablecause().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.probableCause");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->probablecause(), output);
  }

  // string uniqueNo = 3;
  if (this->uniqueno().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->uniqueno().data(), static_cast<int>(this->uniqueno().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.uniqueNo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->uniqueno(), output);
  }

  // string stb = 4;
  if (this->stb().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stb().data(), static_cast<int>(this->stb().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.stb");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->stb(), output);
  }

  // string createTime = 5;
  if (this->createtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->createtime().data(), static_cast<int>(this->createtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.createTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->createtime(), output);
  }

  // string entityInstance = 6;
  if (this->entityinstance().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entityinstance().data(), static_cast<int>(this->entityinstance().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.entityInstance");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->entityinstance(), output);
  }

  // .proto.EnumDefineData.AppTypeEnum appTypeCode = 7;
  if (this->apptypecode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      7, this->apptypecode(), output);
  }

  // string messageFormat = 8;
  if (this->messageformat().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messageformat().data(), static_cast<int>(this->messageformat().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.messageFormat");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->messageformat(), output);
  }

  // string message = 9;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->message(), output);
  }

  // string desp = 10;
  if (this->desp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->desp().data(), static_cast<int>(this->desp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.desp");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->desp(), output);
  }

  // .proto.AcsEventData.TmCtrlTypeEnum ctrlType = 11;
  if (this->ctrltype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      11, this->ctrltype(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.AcsEventData)
}

::google::protobuf::uint8* AcsEventData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.AcsEventData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string messageType = 1;
  if (this->messagetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messagetype().data(), static_cast<int>(this->messagetype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.messageType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->messagetype(), target);
  }

  // string probableCause = 2;
  if (this->probablecause().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->probablecause().data(), static_cast<int>(this->probablecause().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.probableCause");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->probablecause(), target);
  }

  // string uniqueNo = 3;
  if (this->uniqueno().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->uniqueno().data(), static_cast<int>(this->uniqueno().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.uniqueNo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->uniqueno(), target);
  }

  // string stb = 4;
  if (this->stb().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stb().data(), static_cast<int>(this->stb().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.stb");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->stb(), target);
  }

  // string createTime = 5;
  if (this->createtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->createtime().data(), static_cast<int>(this->createtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.createTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->createtime(), target);
  }

  // string entityInstance = 6;
  if (this->entityinstance().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entityinstance().data(), static_cast<int>(this->entityinstance().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.entityInstance");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->entityinstance(), target);
  }

  // .proto.EnumDefineData.AppTypeEnum appTypeCode = 7;
  if (this->apptypecode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      7, this->apptypecode(), target);
  }

  // string messageFormat = 8;
  if (this->messageformat().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messageformat().data(), static_cast<int>(this->messageformat().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.messageFormat");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->messageformat(), target);
  }

  // string message = 9;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->message(), target);
  }

  // string desp = 10;
  if (this->desp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->desp().data(), static_cast<int>(this->desp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.AcsEventData.desp");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->desp(), target);
  }

  // .proto.AcsEventData.TmCtrlTypeEnum ctrlType = 11;
  if (this->ctrltype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      11, this->ctrltype(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.AcsEventData)
  return target;
}

size_t AcsEventData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.AcsEventData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string messageType = 1;
  if (this->messagetype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->messagetype());
  }

  // string probableCause = 2;
  if (this->probablecause().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->probablecause());
  }

  // string uniqueNo = 3;
  if (this->uniqueno().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->uniqueno());
  }

  // string stb = 4;
  if (this->stb().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stb());
  }

  // string createTime = 5;
  if (this->createtime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->createtime());
  }

  // string entityInstance = 6;
  if (this->entityinstance().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->entityinstance());
  }

  // string messageFormat = 8;
  if (this->messageformat().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->messageformat());
  }

  // string message = 9;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // string desp = 10;
  if (this->desp().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->desp());
  }

  // .proto.EnumDefineData.AppTypeEnum appTypeCode = 7;
  if (this->apptypecode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->apptypecode());
  }

  // .proto.AcsEventData.TmCtrlTypeEnum ctrlType = 11;
  if (this->ctrltype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ctrltype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AcsEventData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.AcsEventData)
  GOOGLE_DCHECK_NE(&from, this);
  const AcsEventData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AcsEventData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.AcsEventData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.AcsEventData)
    MergeFrom(*source);
  }
}

void AcsEventData::MergeFrom(const AcsEventData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.AcsEventData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.messagetype().size() > 0) {

    messagetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messagetype_);
  }
  if (from.probablecause().size() > 0) {

    probablecause_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.probablecause_);
  }
  if (from.uniqueno().size() > 0) {

    uniqueno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uniqueno_);
  }
  if (from.stb().size() > 0) {

    stb_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stb_);
  }
  if (from.createtime().size() > 0) {

    createtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.createtime_);
  }
  if (from.entityinstance().size() > 0) {

    entityinstance_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entityinstance_);
  }
  if (from.messageformat().size() > 0) {

    messageformat_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messageformat_);
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.desp().size() > 0) {

    desp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.desp_);
  }
  if (from.apptypecode() != 0) {
    set_apptypecode(from.apptypecode());
  }
  if (from.ctrltype() != 0) {
    set_ctrltype(from.ctrltype());
  }
}

void AcsEventData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.AcsEventData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AcsEventData::CopyFrom(const AcsEventData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.AcsEventData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AcsEventData::IsInitialized() const {
  return true;
}

void AcsEventData::Swap(AcsEventData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AcsEventData::InternalSwap(AcsEventData* other) {
  using std::swap;
  messagetype_.Swap(&other->messagetype_);
  probablecause_.Swap(&other->probablecause_);
  uniqueno_.Swap(&other->uniqueno_);
  stb_.Swap(&other->stb_);
  createtime_.Swap(&other->createtime_);
  entityinstance_.Swap(&other->entityinstance_);
  messageformat_.Swap(&other->messageformat_);
  message_.Swap(&other->message_);
  desp_.Swap(&other->desp_);
  swap(apptypecode_, other->apptypecode_);
  swap(ctrltype_, other->ctrltype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AcsEventData::GetMetadata() const {
  protobuf_AcsEvent_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_AcsEvent_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AcsEventData

// string messageType = 1;
void AcsEventData::clear_messagetype() {
  messagetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::messagetype() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.messageType)
  return messagetype_.GetNoArena();
}
void AcsEventData::set_messagetype(const ::std::string& value) {
  
  messagetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.messageType)
}
#if LANG_CXX11
void AcsEventData::set_messagetype(::std::string&& value) {
  
  messagetype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.messageType)
}
#endif
void AcsEventData::set_messagetype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  messagetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.messageType)
}
void AcsEventData::set_messagetype(const char* value, size_t size) {
  
  messagetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.messageType)
}
::std::string* AcsEventData::mutable_messagetype() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.messageType)
  return messagetype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_messagetype() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.messageType)
  
  return messagetype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_messagetype(::std::string* messagetype) {
  if (messagetype != NULL) {
    
  } else {
    
  }
  messagetype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messagetype);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.messageType)
}

// string probableCause = 2;
void AcsEventData::clear_probablecause() {
  probablecause_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::probablecause() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.probableCause)
  return probablecause_.GetNoArena();
}
void AcsEventData::set_probablecause(const ::std::string& value) {
  
  probablecause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.probableCause)
}
#if LANG_CXX11
void AcsEventData::set_probablecause(::std::string&& value) {
  
  probablecause_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.probableCause)
}
#endif
void AcsEventData::set_probablecause(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  probablecause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.probableCause)
}
void AcsEventData::set_probablecause(const char* value, size_t size) {
  
  probablecause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.probableCause)
}
::std::string* AcsEventData::mutable_probablecause() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.probableCause)
  return probablecause_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_probablecause() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.probableCause)
  
  return probablecause_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_probablecause(::std::string* probablecause) {
  if (probablecause != NULL) {
    
  } else {
    
  }
  probablecause_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), probablecause);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.probableCause)
}

// string uniqueNo = 3;
void AcsEventData::clear_uniqueno() {
  uniqueno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::uniqueno() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.uniqueNo)
  return uniqueno_.GetNoArena();
}
void AcsEventData::set_uniqueno(const ::std::string& value) {
  
  uniqueno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.uniqueNo)
}
#if LANG_CXX11
void AcsEventData::set_uniqueno(::std::string&& value) {
  
  uniqueno_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.uniqueNo)
}
#endif
void AcsEventData::set_uniqueno(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  uniqueno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.uniqueNo)
}
void AcsEventData::set_uniqueno(const char* value, size_t size) {
  
  uniqueno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.uniqueNo)
}
::std::string* AcsEventData::mutable_uniqueno() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.uniqueNo)
  return uniqueno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_uniqueno() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.uniqueNo)
  
  return uniqueno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_uniqueno(::std::string* uniqueno) {
  if (uniqueno != NULL) {
    
  } else {
    
  }
  uniqueno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uniqueno);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.uniqueNo)
}

// string stb = 4;
void AcsEventData::clear_stb() {
  stb_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::stb() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.stb)
  return stb_.GetNoArena();
}
void AcsEventData::set_stb(const ::std::string& value) {
  
  stb_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.stb)
}
#if LANG_CXX11
void AcsEventData::set_stb(::std::string&& value) {
  
  stb_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.stb)
}
#endif
void AcsEventData::set_stb(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  stb_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.stb)
}
void AcsEventData::set_stb(const char* value, size_t size) {
  
  stb_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.stb)
}
::std::string* AcsEventData::mutable_stb() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.stb)
  return stb_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_stb() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.stb)
  
  return stb_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_stb(::std::string* stb) {
  if (stb != NULL) {
    
  } else {
    
  }
  stb_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stb);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.stb)
}

// string createTime = 5;
void AcsEventData::clear_createtime() {
  createtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::createtime() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.createTime)
  return createtime_.GetNoArena();
}
void AcsEventData::set_createtime(const ::std::string& value) {
  
  createtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.createTime)
}
#if LANG_CXX11
void AcsEventData::set_createtime(::std::string&& value) {
  
  createtime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.createTime)
}
#endif
void AcsEventData::set_createtime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  createtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.createTime)
}
void AcsEventData::set_createtime(const char* value, size_t size) {
  
  createtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.createTime)
}
::std::string* AcsEventData::mutable_createtime() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.createTime)
  return createtime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_createtime() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.createTime)
  
  return createtime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_createtime(::std::string* createtime) {
  if (createtime != NULL) {
    
  } else {
    
  }
  createtime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), createtime);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.createTime)
}

// string entityInstance = 6;
void AcsEventData::clear_entityinstance() {
  entityinstance_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::entityinstance() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.entityInstance)
  return entityinstance_.GetNoArena();
}
void AcsEventData::set_entityinstance(const ::std::string& value) {
  
  entityinstance_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.entityInstance)
}
#if LANG_CXX11
void AcsEventData::set_entityinstance(::std::string&& value) {
  
  entityinstance_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.entityInstance)
}
#endif
void AcsEventData::set_entityinstance(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  entityinstance_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.entityInstance)
}
void AcsEventData::set_entityinstance(const char* value, size_t size) {
  
  entityinstance_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.entityInstance)
}
::std::string* AcsEventData::mutable_entityinstance() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.entityInstance)
  return entityinstance_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_entityinstance() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.entityInstance)
  
  return entityinstance_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_entityinstance(::std::string* entityinstance) {
  if (entityinstance != NULL) {
    
  } else {
    
  }
  entityinstance_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), entityinstance);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.entityInstance)
}

// .proto.EnumDefineData.AppTypeEnum appTypeCode = 7;
void AcsEventData::clear_apptypecode() {
  apptypecode_ = 0;
}
::proto::EnumDefineData_AppTypeEnum AcsEventData::apptypecode() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.appTypeCode)
  return static_cast< ::proto::EnumDefineData_AppTypeEnum >(apptypecode_);
}
void AcsEventData::set_apptypecode(::proto::EnumDefineData_AppTypeEnum value) {
  
  apptypecode_ = value;
  // @@protoc_insertion_point(field_set:proto.AcsEventData.appTypeCode)
}

// string messageFormat = 8;
void AcsEventData::clear_messageformat() {
  messageformat_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::messageformat() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.messageFormat)
  return messageformat_.GetNoArena();
}
void AcsEventData::set_messageformat(const ::std::string& value) {
  
  messageformat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.messageFormat)
}
#if LANG_CXX11
void AcsEventData::set_messageformat(::std::string&& value) {
  
  messageformat_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.messageFormat)
}
#endif
void AcsEventData::set_messageformat(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  messageformat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.messageFormat)
}
void AcsEventData::set_messageformat(const char* value, size_t size) {
  
  messageformat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.messageFormat)
}
::std::string* AcsEventData::mutable_messageformat() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.messageFormat)
  return messageformat_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_messageformat() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.messageFormat)
  
  return messageformat_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_messageformat(::std::string* messageformat) {
  if (messageformat != NULL) {
    
  } else {
    
  }
  messageformat_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messageformat);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.messageFormat)
}

// string message = 9;
void AcsEventData::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::message() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.message)
  return message_.GetNoArena();
}
void AcsEventData::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.message)
}
#if LANG_CXX11
void AcsEventData::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.message)
}
#endif
void AcsEventData::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.message)
}
void AcsEventData::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.message)
}
::std::string* AcsEventData::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_message() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.message)
}

// string desp = 10;
void AcsEventData::clear_desp() {
  desp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AcsEventData::desp() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.desp)
  return desp_.GetNoArena();
}
void AcsEventData::set_desp(const ::std::string& value) {
  
  desp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.AcsEventData.desp)
}
#if LANG_CXX11
void AcsEventData::set_desp(::std::string&& value) {
  
  desp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.AcsEventData.desp)
}
#endif
void AcsEventData::set_desp(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  desp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.AcsEventData.desp)
}
void AcsEventData::set_desp(const char* value, size_t size) {
  
  desp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.AcsEventData.desp)
}
::std::string* AcsEventData::mutable_desp() {
  
  // @@protoc_insertion_point(field_mutable:proto.AcsEventData.desp)
  return desp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AcsEventData::release_desp() {
  // @@protoc_insertion_point(field_release:proto.AcsEventData.desp)
  
  return desp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AcsEventData::set_allocated_desp(::std::string* desp) {
  if (desp != NULL) {
    
  } else {
    
  }
  desp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), desp);
  // @@protoc_insertion_point(field_set_allocated:proto.AcsEventData.desp)
}

// .proto.AcsEventData.TmCtrlTypeEnum ctrlType = 11;
void AcsEventData::clear_ctrltype() {
  ctrltype_ = 0;
}
::proto::AcsEventData_TmCtrlTypeEnum AcsEventData::ctrltype() const {
  // @@protoc_insertion_point(field_get:proto.AcsEventData.ctrlType)
  return static_cast< ::proto::AcsEventData_TmCtrlTypeEnum >(ctrltype_);
}
void AcsEventData::set_ctrltype(::proto::AcsEventData_TmCtrlTypeEnum value) {
  
  ctrltype_ = value;
  // @@protoc_insertion_point(field_set:proto.AcsEventData.ctrlType)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)
