// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HaSwitch.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "HaSwitch.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace fiberhome {
namespace fums {
namespace proto {
class HaSwitchDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HaSwitchData>
     _instance;
} _HaSwitchData_default_instance_;
class HaSwitchResponseDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HaSwitchResponse>
     _instance;
} _HaSwitchResponse_default_instance_;

namespace protobuf_HaSwitch_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchData, uniqueid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchData, haswitchtype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchData, apptype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchData, apptypecode_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchResponse, uniqueid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchResponse, haswitchtype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HaSwitchResponse, hastatus_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(HaSwitchData)},
  { 9, -1, sizeof(HaSwitchResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_HaSwitchData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_HaSwitchResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "HaSwitch.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::com::fiberhome::fums::proto::protobuf_CommonDefine_2eproto::InitDefaults();
  _HaSwitchData_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_HaSwitchData_default_instance_);_HaSwitchResponse_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_HaSwitchResponse_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016HaSwitch.proto\022\030com.fiberhome.fums.pro"
      "to\032\022CommonDefine.proto\"\374\001\n\014HaSwitchData\022"
      "\020\n\010uniqueId\030\001 \001(\003\022M\n\014haSwitchType\030\002 \001(\0162"
      "7.com.fiberhome.fums.proto.HaSwitchData."
      "HaSwitchTypeEnum\022\017\n\007appType\030\003 \001(\t\022I\n\013app"
      "TypeCode\030\004 \001(\01624.com.fiberhome.fums.prot"
      "o.EnumDefineData.AppTypeEnum\"/\n\020HaSwitch"
      "TypeEnum\022\r\n\tSWITCH_HA\020\000\022\014\n\010QUERY_HA\020\001\"\205\001"
      "\n\020HaSwitchResponse\022\020\n\010uniqueId\030\001 \001(\003\022M\n\014"
      "haSwitchType\030\002 \001(\01627.com.fiberhome.fums."
      "proto.HaSwitchData.HaSwitchTypeEnum\022\020\n\010h"
      "aStatus\030\003 \001(\005B$\n\030com.fiberhome.fums.prot"
      "oB\010HaSwitchb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 499);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "HaSwitch.proto", &protobuf_RegisterTypes);
  ::com::fiberhome::fums::proto::protobuf_CommonDefine_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_HaSwitch_2eproto

const ::google::protobuf::EnumDescriptor* HaSwitchData_HaSwitchTypeEnum_descriptor() {
  protobuf_HaSwitch_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_HaSwitch_2eproto::file_level_enum_descriptors[0];
}
bool HaSwitchData_HaSwitchTypeEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const HaSwitchData_HaSwitchTypeEnum HaSwitchData::SWITCH_HA;
const HaSwitchData_HaSwitchTypeEnum HaSwitchData::QUERY_HA;
const HaSwitchData_HaSwitchTypeEnum HaSwitchData::HaSwitchTypeEnum_MIN;
const HaSwitchData_HaSwitchTypeEnum HaSwitchData::HaSwitchTypeEnum_MAX;
const int HaSwitchData::HaSwitchTypeEnum_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HaSwitchData::kUniqueIdFieldNumber;
const int HaSwitchData::kHaSwitchTypeFieldNumber;
const int HaSwitchData::kAppTypeFieldNumber;
const int HaSwitchData::kAppTypeCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HaSwitchData::HaSwitchData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_HaSwitch_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.fiberhome.fums.proto.HaSwitchData)
}
HaSwitchData::HaSwitchData(const HaSwitchData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  apptype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.apptype().size() > 0) {
    apptype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apptype_);
  }
  ::memcpy(&uniqueid_, &from.uniqueid_,
    static_cast<size_t>(reinterpret_cast<char*>(&apptypecode_) -
    reinterpret_cast<char*>(&uniqueid_)) + sizeof(apptypecode_));
  // @@protoc_insertion_point(copy_constructor:com.fiberhome.fums.proto.HaSwitchData)
}

void HaSwitchData::SharedCtor() {
  apptype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uniqueid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&apptypecode_) -
      reinterpret_cast<char*>(&uniqueid_)) + sizeof(apptypecode_));
  _cached_size_ = 0;
}

HaSwitchData::~HaSwitchData() {
  // @@protoc_insertion_point(destructor:com.fiberhome.fums.proto.HaSwitchData)
  SharedDtor();
}

void HaSwitchData::SharedDtor() {
  apptype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void HaSwitchData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HaSwitchData::descriptor() {
  protobuf_HaSwitch_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_HaSwitch_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HaSwitchData& HaSwitchData::default_instance() {
  protobuf_HaSwitch_2eproto::InitDefaults();
  return *internal_default_instance();
}

HaSwitchData* HaSwitchData::New(::google::protobuf::Arena* arena) const {
  HaSwitchData* n = new HaSwitchData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HaSwitchData::Clear() {
// @@protoc_insertion_point(message_clear_start:com.fiberhome.fums.proto.HaSwitchData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  apptype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uniqueid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&apptypecode_) -
      reinterpret_cast<char*>(&uniqueid_)) + sizeof(apptypecode_));
  _internal_metadata_.Clear();
}

bool HaSwitchData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.fiberhome.fums.proto.HaSwitchData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 uniqueId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &uniqueid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_haswitchtype(static_cast< ::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string appType = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_apptype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->apptype().data(), static_cast<int>(this->apptype().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.fiberhome.fums.proto.HaSwitchData.appType"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .com.fiberhome.fums.proto.EnumDefineData.AppTypeEnum appTypeCode = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_apptypecode(static_cast< ::com::fiberhome::fums::proto::EnumDefineData_AppTypeEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.fiberhome.fums.proto.HaSwitchData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.fiberhome.fums.proto.HaSwitchData)
  return false;
#undef DO_
}

void HaSwitchData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.fiberhome.fums.proto.HaSwitchData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uniqueId = 1;
  if (this->uniqueid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->uniqueid(), output);
  }

  // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
  if (this->haswitchtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->haswitchtype(), output);
  }

  // string appType = 3;
  if (this->apptype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->apptype().data(), static_cast<int>(this->apptype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.fiberhome.fums.proto.HaSwitchData.appType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->apptype(), output);
  }

  // .com.fiberhome.fums.proto.EnumDefineData.AppTypeEnum appTypeCode = 4;
  if (this->apptypecode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->apptypecode(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:com.fiberhome.fums.proto.HaSwitchData)
}

::google::protobuf::uint8* HaSwitchData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:com.fiberhome.fums.proto.HaSwitchData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uniqueId = 1;
  if (this->uniqueid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->uniqueid(), target);
  }

  // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
  if (this->haswitchtype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->haswitchtype(), target);
  }

  // string appType = 3;
  if (this->apptype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->apptype().data(), static_cast<int>(this->apptype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.fiberhome.fums.proto.HaSwitchData.appType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->apptype(), target);
  }

  // .com.fiberhome.fums.proto.EnumDefineData.AppTypeEnum appTypeCode = 4;
  if (this->apptypecode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->apptypecode(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.fiberhome.fums.proto.HaSwitchData)
  return target;
}

size_t HaSwitchData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.fiberhome.fums.proto.HaSwitchData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string appType = 3;
  if (this->apptype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->apptype());
  }

  // int64 uniqueId = 1;
  if (this->uniqueid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->uniqueid());
  }

  // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
  if (this->haswitchtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->haswitchtype());
  }

  // .com.fiberhome.fums.proto.EnumDefineData.AppTypeEnum appTypeCode = 4;
  if (this->apptypecode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->apptypecode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HaSwitchData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.fiberhome.fums.proto.HaSwitchData)
  GOOGLE_DCHECK_NE(&from, this);
  const HaSwitchData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HaSwitchData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.fiberhome.fums.proto.HaSwitchData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.fiberhome.fums.proto.HaSwitchData)
    MergeFrom(*source);
  }
}

void HaSwitchData::MergeFrom(const HaSwitchData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.fiberhome.fums.proto.HaSwitchData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.apptype().size() > 0) {

    apptype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apptype_);
  }
  if (from.uniqueid() != 0) {
    set_uniqueid(from.uniqueid());
  }
  if (from.haswitchtype() != 0) {
    set_haswitchtype(from.haswitchtype());
  }
  if (from.apptypecode() != 0) {
    set_apptypecode(from.apptypecode());
  }
}

void HaSwitchData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.fiberhome.fums.proto.HaSwitchData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HaSwitchData::CopyFrom(const HaSwitchData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.fiberhome.fums.proto.HaSwitchData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HaSwitchData::IsInitialized() const {
  return true;
}

void HaSwitchData::Swap(HaSwitchData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HaSwitchData::InternalSwap(HaSwitchData* other) {
  using std::swap;
  apptype_.Swap(&other->apptype_);
  swap(uniqueid_, other->uniqueid_);
  swap(haswitchtype_, other->haswitchtype_);
  swap(apptypecode_, other->apptypecode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HaSwitchData::GetMetadata() const {
  protobuf_HaSwitch_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_HaSwitch_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HaSwitchData

// int64 uniqueId = 1;
void HaSwitchData::clear_uniqueid() {
  uniqueid_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 HaSwitchData::uniqueid() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchData.uniqueId)
  return uniqueid_;
}
void HaSwitchData::set_uniqueid(::google::protobuf::int64 value) {
  
  uniqueid_ = value;
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchData.uniqueId)
}

// .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
void HaSwitchData::clear_haswitchtype() {
  haswitchtype_ = 0;
}
::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum HaSwitchData::haswitchtype() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchData.haSwitchType)
  return static_cast< ::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum >(haswitchtype_);
}
void HaSwitchData::set_haswitchtype(::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum value) {
  
  haswitchtype_ = value;
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchData.haSwitchType)
}

// string appType = 3;
void HaSwitchData::clear_apptype() {
  apptype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& HaSwitchData::apptype() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchData.appType)
  return apptype_.GetNoArena();
}
void HaSwitchData::set_apptype(const ::std::string& value) {
  
  apptype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchData.appType)
}
#if LANG_CXX11
void HaSwitchData::set_apptype(::std::string&& value) {
  
  apptype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.fiberhome.fums.proto.HaSwitchData.appType)
}
#endif
void HaSwitchData::set_apptype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  apptype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.fiberhome.fums.proto.HaSwitchData.appType)
}
void HaSwitchData::set_apptype(const char* value, size_t size) {
  
  apptype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.fiberhome.fums.proto.HaSwitchData.appType)
}
::std::string* HaSwitchData::mutable_apptype() {
  
  // @@protoc_insertion_point(field_mutable:com.fiberhome.fums.proto.HaSwitchData.appType)
  return apptype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* HaSwitchData::release_apptype() {
  // @@protoc_insertion_point(field_release:com.fiberhome.fums.proto.HaSwitchData.appType)
  
  return apptype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void HaSwitchData::set_allocated_apptype(::std::string* apptype) {
  if (apptype != NULL) {
    
  } else {
    
  }
  apptype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), apptype);
  // @@protoc_insertion_point(field_set_allocated:com.fiberhome.fums.proto.HaSwitchData.appType)
}

// .com.fiberhome.fums.proto.EnumDefineData.AppTypeEnum appTypeCode = 4;
void HaSwitchData::clear_apptypecode() {
  apptypecode_ = 0;
}
::com::fiberhome::fums::proto::EnumDefineData_AppTypeEnum HaSwitchData::apptypecode() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchData.appTypeCode)
  return static_cast< ::com::fiberhome::fums::proto::EnumDefineData_AppTypeEnum >(apptypecode_);
}
void HaSwitchData::set_apptypecode(::com::fiberhome::fums::proto::EnumDefineData_AppTypeEnum value) {
  
  apptypecode_ = value;
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchData.appTypeCode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HaSwitchResponse::kUniqueIdFieldNumber;
const int HaSwitchResponse::kHaSwitchTypeFieldNumber;
const int HaSwitchResponse::kHaStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HaSwitchResponse::HaSwitchResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_HaSwitch_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.fiberhome.fums.proto.HaSwitchResponse)
}
HaSwitchResponse::HaSwitchResponse(const HaSwitchResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&uniqueid_, &from.uniqueid_,
    static_cast<size_t>(reinterpret_cast<char*>(&hastatus_) -
    reinterpret_cast<char*>(&uniqueid_)) + sizeof(hastatus_));
  // @@protoc_insertion_point(copy_constructor:com.fiberhome.fums.proto.HaSwitchResponse)
}

void HaSwitchResponse::SharedCtor() {
  ::memset(&uniqueid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hastatus_) -
      reinterpret_cast<char*>(&uniqueid_)) + sizeof(hastatus_));
  _cached_size_ = 0;
}

HaSwitchResponse::~HaSwitchResponse() {
  // @@protoc_insertion_point(destructor:com.fiberhome.fums.proto.HaSwitchResponse)
  SharedDtor();
}

void HaSwitchResponse::SharedDtor() {
}

void HaSwitchResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HaSwitchResponse::descriptor() {
  protobuf_HaSwitch_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_HaSwitch_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HaSwitchResponse& HaSwitchResponse::default_instance() {
  protobuf_HaSwitch_2eproto::InitDefaults();
  return *internal_default_instance();
}

HaSwitchResponse* HaSwitchResponse::New(::google::protobuf::Arena* arena) const {
  HaSwitchResponse* n = new HaSwitchResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HaSwitchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:com.fiberhome.fums.proto.HaSwitchResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&uniqueid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hastatus_) -
      reinterpret_cast<char*>(&uniqueid_)) + sizeof(hastatus_));
  _internal_metadata_.Clear();
}

bool HaSwitchResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.fiberhome.fums.proto.HaSwitchResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 uniqueId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &uniqueid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_haswitchtype(static_cast< ::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 haStatus = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hastatus_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.fiberhome.fums.proto.HaSwitchResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.fiberhome.fums.proto.HaSwitchResponse)
  return false;
#undef DO_
}

void HaSwitchResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.fiberhome.fums.proto.HaSwitchResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uniqueId = 1;
  if (this->uniqueid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->uniqueid(), output);
  }

  // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
  if (this->haswitchtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->haswitchtype(), output);
  }

  // int32 haStatus = 3;
  if (this->hastatus() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->hastatus(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:com.fiberhome.fums.proto.HaSwitchResponse)
}

::google::protobuf::uint8* HaSwitchResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:com.fiberhome.fums.proto.HaSwitchResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 uniqueId = 1;
  if (this->uniqueid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->uniqueid(), target);
  }

  // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
  if (this->haswitchtype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->haswitchtype(), target);
  }

  // int32 haStatus = 3;
  if (this->hastatus() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->hastatus(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.fiberhome.fums.proto.HaSwitchResponse)
  return target;
}

size_t HaSwitchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.fiberhome.fums.proto.HaSwitchResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 uniqueId = 1;
  if (this->uniqueid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->uniqueid());
  }

  // .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
  if (this->haswitchtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->haswitchtype());
  }

  // int32 haStatus = 3;
  if (this->hastatus() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->hastatus());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HaSwitchResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.fiberhome.fums.proto.HaSwitchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const HaSwitchResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HaSwitchResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.fiberhome.fums.proto.HaSwitchResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.fiberhome.fums.proto.HaSwitchResponse)
    MergeFrom(*source);
  }
}

void HaSwitchResponse::MergeFrom(const HaSwitchResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.fiberhome.fums.proto.HaSwitchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uniqueid() != 0) {
    set_uniqueid(from.uniqueid());
  }
  if (from.haswitchtype() != 0) {
    set_haswitchtype(from.haswitchtype());
  }
  if (from.hastatus() != 0) {
    set_hastatus(from.hastatus());
  }
}

void HaSwitchResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.fiberhome.fums.proto.HaSwitchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HaSwitchResponse::CopyFrom(const HaSwitchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.fiberhome.fums.proto.HaSwitchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HaSwitchResponse::IsInitialized() const {
  return true;
}

void HaSwitchResponse::Swap(HaSwitchResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HaSwitchResponse::InternalSwap(HaSwitchResponse* other) {
  using std::swap;
  swap(uniqueid_, other->uniqueid_);
  swap(haswitchtype_, other->haswitchtype_);
  swap(hastatus_, other->hastatus_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HaSwitchResponse::GetMetadata() const {
  protobuf_HaSwitch_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_HaSwitch_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HaSwitchResponse

// int64 uniqueId = 1;
void HaSwitchResponse::clear_uniqueid() {
  uniqueid_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 HaSwitchResponse::uniqueid() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchResponse.uniqueId)
  return uniqueid_;
}
void HaSwitchResponse::set_uniqueid(::google::protobuf::int64 value) {
  
  uniqueid_ = value;
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchResponse.uniqueId)
}

// .com.fiberhome.fums.proto.HaSwitchData.HaSwitchTypeEnum haSwitchType = 2;
void HaSwitchResponse::clear_haswitchtype() {
  haswitchtype_ = 0;
}
::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum HaSwitchResponse::haswitchtype() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchResponse.haSwitchType)
  return static_cast< ::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum >(haswitchtype_);
}
void HaSwitchResponse::set_haswitchtype(::com::fiberhome::fums::proto::HaSwitchData_HaSwitchTypeEnum value) {
  
  haswitchtype_ = value;
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchResponse.haSwitchType)
}

// int32 haStatus = 3;
void HaSwitchResponse::clear_hastatus() {
  hastatus_ = 0;
}
::google::protobuf::int32 HaSwitchResponse::hastatus() const {
  // @@protoc_insertion_point(field_get:com.fiberhome.fums.proto.HaSwitchResponse.haStatus)
  return hastatus_;
}
void HaSwitchResponse::set_hastatus(::google::protobuf::int32 value) {
  
  hastatus_ = value;
  // @@protoc_insertion_point(field_set:com.fiberhome.fums.proto.HaSwitchResponse.haStatus)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace fums
}  // namespace fiberhome
}  // namespace com

// @@protoc_insertion_point(global_scope)
