// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StbInspect.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "StbInspect.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
class StbInspectDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<StbInspectData>
     _instance;
} _StbInspectData_default_instance_;

namespace protobuf_StbInspect_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, messagetype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, stbip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, entitytype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, entityinstance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, apptypecode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, operdirect_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, opername_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, operarglist_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, operrst_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, operoccurtime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StbInspectData, desp_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(StbInspectData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_StbInspectData_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "StbInspect.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::proto::protobuf_CommonDefine_2eproto::InitDefaults();
  _StbInspectData_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_StbInspectData_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020StbInspect.proto\022\005proto\032\022CommonDefine."
      "proto\"\211\002\n\016StbInspectData\022\023\n\013messageType\030"
      "\001 \001(\t\022\r\n\005stbIp\030\002 \001(\t\022\022\n\nentityType\030\003 \001(\t"
      "\022\026\n\016entityInstance\030\004 \001(\t\0226\n\013appTypeCode\030"
      "\005 \001(\0162!.proto.EnumDefineData.AppTypeEnum"
      "\022\022\n\noperDirect\030\006 \001(\t\022\020\n\010operName\030\007 \001(\t\022\023"
      "\n\013operArgList\030\010 \001(\t\022\017\n\007operRst\030\t \001(\t\022\025\n\r"
      "operOccurTime\030\n \001(\t\022\014\n\004desp\030\013 \001(\tB&\n\030com"
      ".fiberhome.fums.protoB\nStbInspectb\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 361);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "StbInspect.proto", &protobuf_RegisterTypes);
  ::proto::protobuf_CommonDefine_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_StbInspect_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StbInspectData::kMessageTypeFieldNumber;
const int StbInspectData::kStbIpFieldNumber;
const int StbInspectData::kEntityTypeFieldNumber;
const int StbInspectData::kEntityInstanceFieldNumber;
const int StbInspectData::kAppTypeCodeFieldNumber;
const int StbInspectData::kOperDirectFieldNumber;
const int StbInspectData::kOperNameFieldNumber;
const int StbInspectData::kOperArgListFieldNumber;
const int StbInspectData::kOperRstFieldNumber;
const int StbInspectData::kOperOccurTimeFieldNumber;
const int StbInspectData::kDespFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StbInspectData::StbInspectData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_StbInspect_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.StbInspectData)
}
StbInspectData::StbInspectData(const StbInspectData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  messagetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.messagetype().size() > 0) {
    messagetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messagetype_);
  }
  stbip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stbip().size() > 0) {
    stbip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stbip_);
  }
  entitytype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.entitytype().size() > 0) {
    entitytype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entitytype_);
  }
  entityinstance_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.entityinstance().size() > 0) {
    entityinstance_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entityinstance_);
  }
  operdirect_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operdirect().size() > 0) {
    operdirect_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operdirect_);
  }
  opername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.opername().size() > 0) {
    opername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.opername_);
  }
  operarglist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operarglist().size() > 0) {
    operarglist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operarglist_);
  }
  operrst_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operrst().size() > 0) {
    operrst_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operrst_);
  }
  operoccurtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operoccurtime().size() > 0) {
    operoccurtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operoccurtime_);
  }
  desp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.desp().size() > 0) {
    desp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.desp_);
  }
  apptypecode_ = from.apptypecode_;
  // @@protoc_insertion_point(copy_constructor:proto.StbInspectData)
}

void StbInspectData::SharedCtor() {
  messagetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stbip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entitytype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entityinstance_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operdirect_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operarglist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operrst_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operoccurtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apptypecode_ = 0;
  _cached_size_ = 0;
}

StbInspectData::~StbInspectData() {
  // @@protoc_insertion_point(destructor:proto.StbInspectData)
  SharedDtor();
}

void StbInspectData::SharedDtor() {
  messagetype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stbip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entitytype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entityinstance_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operdirect_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opername_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operarglist_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operrst_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operoccurtime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desp_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StbInspectData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StbInspectData::descriptor() {
  protobuf_StbInspect_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_StbInspect_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StbInspectData& StbInspectData::default_instance() {
  protobuf_StbInspect_2eproto::InitDefaults();
  return *internal_default_instance();
}

StbInspectData* StbInspectData::New(::google::protobuf::Arena* arena) const {
  StbInspectData* n = new StbInspectData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StbInspectData::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.StbInspectData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messagetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stbip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entitytype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  entityinstance_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operdirect_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operarglist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operrst_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operoccurtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  desp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apptypecode_ = 0;
  _internal_metadata_.Clear();
}

bool StbInspectData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.StbInspectData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string messageType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_messagetype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->messagetype().data(), static_cast<int>(this->messagetype().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.messageType"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stbIp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stbip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stbip().data(), static_cast<int>(this->stbip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.stbIp"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string entityType = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_entitytype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->entitytype().data(), static_cast<int>(this->entitytype().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.entityType"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string entityInstance = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_entityinstance()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->entityinstance().data(), static_cast<int>(this->entityinstance().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.entityInstance"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .proto.EnumDefineData.AppTypeEnum appTypeCode = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_apptypecode(static_cast< ::proto::EnumDefineData_AppTypeEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operDirect = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operdirect()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operdirect().data(), static_cast<int>(this->operdirect().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.operDirect"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operName = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_opername()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->opername().data(), static_cast<int>(this->opername().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.operName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operArgList = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operarglist()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operarglist().data(), static_cast<int>(this->operarglist().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.operArgList"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operRst = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operrst()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operrst().data(), static_cast<int>(this->operrst().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.operRst"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operOccurTime = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operoccurtime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operoccurtime().data(), static_cast<int>(this->operoccurtime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.operOccurTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string desp = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_desp()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->desp().data(), static_cast<int>(this->desp().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.StbInspectData.desp"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.StbInspectData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.StbInspectData)
  return false;
#undef DO_
}

void StbInspectData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.StbInspectData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string messageType = 1;
  if (this->messagetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messagetype().data(), static_cast<int>(this->messagetype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.messageType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->messagetype(), output);
  }

  // string stbIp = 2;
  if (this->stbip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stbip().data(), static_cast<int>(this->stbip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.stbIp");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->stbip(), output);
  }

  // string entityType = 3;
  if (this->entitytype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entitytype().data(), static_cast<int>(this->entitytype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.entityType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->entitytype(), output);
  }

  // string entityInstance = 4;
  if (this->entityinstance().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entityinstance().data(), static_cast<int>(this->entityinstance().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.entityInstance");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->entityinstance(), output);
  }

  // .proto.EnumDefineData.AppTypeEnum appTypeCode = 5;
  if (this->apptypecode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->apptypecode(), output);
  }

  // string operDirect = 6;
  if (this->operdirect().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operdirect().data(), static_cast<int>(this->operdirect().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operDirect");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->operdirect(), output);
  }

  // string operName = 7;
  if (this->opername().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->opername().data(), static_cast<int>(this->opername().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->opername(), output);
  }

  // string operArgList = 8;
  if (this->operarglist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operarglist().data(), static_cast<int>(this->operarglist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operArgList");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->operarglist(), output);
  }

  // string operRst = 9;
  if (this->operrst().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operrst().data(), static_cast<int>(this->operrst().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operRst");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->operrst(), output);
  }

  // string operOccurTime = 10;
  if (this->operoccurtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operoccurtime().data(), static_cast<int>(this->operoccurtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operOccurTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->operoccurtime(), output);
  }

  // string desp = 11;
  if (this->desp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->desp().data(), static_cast<int>(this->desp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.desp");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->desp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.StbInspectData)
}

::google::protobuf::uint8* StbInspectData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.StbInspectData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string messageType = 1;
  if (this->messagetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messagetype().data(), static_cast<int>(this->messagetype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.messageType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->messagetype(), target);
  }

  // string stbIp = 2;
  if (this->stbip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stbip().data(), static_cast<int>(this->stbip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.stbIp");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->stbip(), target);
  }

  // string entityType = 3;
  if (this->entitytype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entitytype().data(), static_cast<int>(this->entitytype().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.entityType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->entitytype(), target);
  }

  // string entityInstance = 4;
  if (this->entityinstance().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entityinstance().data(), static_cast<int>(this->entityinstance().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.entityInstance");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->entityinstance(), target);
  }

  // .proto.EnumDefineData.AppTypeEnum appTypeCode = 5;
  if (this->apptypecode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->apptypecode(), target);
  }

  // string operDirect = 6;
  if (this->operdirect().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operdirect().data(), static_cast<int>(this->operdirect().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operDirect");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->operdirect(), target);
  }

  // string operName = 7;
  if (this->opername().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->opername().data(), static_cast<int>(this->opername().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->opername(), target);
  }

  // string operArgList = 8;
  if (this->operarglist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operarglist().data(), static_cast<int>(this->operarglist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operArgList");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->operarglist(), target);
  }

  // string operRst = 9;
  if (this->operrst().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operrst().data(), static_cast<int>(this->operrst().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operRst");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->operrst(), target);
  }

  // string operOccurTime = 10;
  if (this->operoccurtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operoccurtime().data(), static_cast<int>(this->operoccurtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.operOccurTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->operoccurtime(), target);
  }

  // string desp = 11;
  if (this->desp().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->desp().data(), static_cast<int>(this->desp().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.StbInspectData.desp");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->desp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.StbInspectData)
  return target;
}

size_t StbInspectData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.StbInspectData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string messageType = 1;
  if (this->messagetype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->messagetype());
  }

  // string stbIp = 2;
  if (this->stbip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stbip());
  }

  // string entityType = 3;
  if (this->entitytype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->entitytype());
  }

  // string entityInstance = 4;
  if (this->entityinstance().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->entityinstance());
  }

  // string operDirect = 6;
  if (this->operdirect().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operdirect());
  }

  // string operName = 7;
  if (this->opername().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->opername());
  }

  // string operArgList = 8;
  if (this->operarglist().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operarglist());
  }

  // string operRst = 9;
  if (this->operrst().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operrst());
  }

  // string operOccurTime = 10;
  if (this->operoccurtime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operoccurtime());
  }

  // string desp = 11;
  if (this->desp().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->desp());
  }

  // .proto.EnumDefineData.AppTypeEnum appTypeCode = 5;
  if (this->apptypecode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->apptypecode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StbInspectData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.StbInspectData)
  GOOGLE_DCHECK_NE(&from, this);
  const StbInspectData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StbInspectData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.StbInspectData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.StbInspectData)
    MergeFrom(*source);
  }
}

void StbInspectData::MergeFrom(const StbInspectData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.StbInspectData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.messagetype().size() > 0) {

    messagetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messagetype_);
  }
  if (from.stbip().size() > 0) {

    stbip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stbip_);
  }
  if (from.entitytype().size() > 0) {

    entitytype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entitytype_);
  }
  if (from.entityinstance().size() > 0) {

    entityinstance_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entityinstance_);
  }
  if (from.operdirect().size() > 0) {

    operdirect_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operdirect_);
  }
  if (from.opername().size() > 0) {

    opername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.opername_);
  }
  if (from.operarglist().size() > 0) {

    operarglist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operarglist_);
  }
  if (from.operrst().size() > 0) {

    operrst_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operrst_);
  }
  if (from.operoccurtime().size() > 0) {

    operoccurtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operoccurtime_);
  }
  if (from.desp().size() > 0) {

    desp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.desp_);
  }
  if (from.apptypecode() != 0) {
    set_apptypecode(from.apptypecode());
  }
}

void StbInspectData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.StbInspectData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StbInspectData::CopyFrom(const StbInspectData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.StbInspectData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StbInspectData::IsInitialized() const {
  return true;
}

void StbInspectData::Swap(StbInspectData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StbInspectData::InternalSwap(StbInspectData* other) {
  using std::swap;
  messagetype_.Swap(&other->messagetype_);
  stbip_.Swap(&other->stbip_);
  entitytype_.Swap(&other->entitytype_);
  entityinstance_.Swap(&other->entityinstance_);
  operdirect_.Swap(&other->operdirect_);
  opername_.Swap(&other->opername_);
  operarglist_.Swap(&other->operarglist_);
  operrst_.Swap(&other->operrst_);
  operoccurtime_.Swap(&other->operoccurtime_);
  desp_.Swap(&other->desp_);
  swap(apptypecode_, other->apptypecode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StbInspectData::GetMetadata() const {
  protobuf_StbInspect_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_StbInspect_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StbInspectData

// string messageType = 1;
void StbInspectData::clear_messagetype() {
  messagetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::messagetype() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.messageType)
  return messagetype_.GetNoArena();
}
void StbInspectData::set_messagetype(const ::std::string& value) {
  
  messagetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.messageType)
}
#if LANG_CXX11
void StbInspectData::set_messagetype(::std::string&& value) {
  
  messagetype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.messageType)
}
#endif
void StbInspectData::set_messagetype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  messagetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.messageType)
}
void StbInspectData::set_messagetype(const char* value, size_t size) {
  
  messagetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.messageType)
}
::std::string* StbInspectData::mutable_messagetype() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.messageType)
  return messagetype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_messagetype() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.messageType)
  
  return messagetype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_messagetype(::std::string* messagetype) {
  if (messagetype != NULL) {
    
  } else {
    
  }
  messagetype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messagetype);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.messageType)
}

// string stbIp = 2;
void StbInspectData::clear_stbip() {
  stbip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::stbip() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.stbIp)
  return stbip_.GetNoArena();
}
void StbInspectData::set_stbip(const ::std::string& value) {
  
  stbip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.stbIp)
}
#if LANG_CXX11
void StbInspectData::set_stbip(::std::string&& value) {
  
  stbip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.stbIp)
}
#endif
void StbInspectData::set_stbip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  stbip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.stbIp)
}
void StbInspectData::set_stbip(const char* value, size_t size) {
  
  stbip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.stbIp)
}
::std::string* StbInspectData::mutable_stbip() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.stbIp)
  return stbip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_stbip() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.stbIp)
  
  return stbip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_stbip(::std::string* stbip) {
  if (stbip != NULL) {
    
  } else {
    
  }
  stbip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stbip);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.stbIp)
}

// string entityType = 3;
void StbInspectData::clear_entitytype() {
  entitytype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::entitytype() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.entityType)
  return entitytype_.GetNoArena();
}
void StbInspectData::set_entitytype(const ::std::string& value) {
  
  entitytype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.entityType)
}
#if LANG_CXX11
void StbInspectData::set_entitytype(::std::string&& value) {
  
  entitytype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.entityType)
}
#endif
void StbInspectData::set_entitytype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  entitytype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.entityType)
}
void StbInspectData::set_entitytype(const char* value, size_t size) {
  
  entitytype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.entityType)
}
::std::string* StbInspectData::mutable_entitytype() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.entityType)
  return entitytype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_entitytype() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.entityType)
  
  return entitytype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_entitytype(::std::string* entitytype) {
  if (entitytype != NULL) {
    
  } else {
    
  }
  entitytype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), entitytype);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.entityType)
}

// string entityInstance = 4;
void StbInspectData::clear_entityinstance() {
  entityinstance_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::entityinstance() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.entityInstance)
  return entityinstance_.GetNoArena();
}
void StbInspectData::set_entityinstance(const ::std::string& value) {
  
  entityinstance_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.entityInstance)
}
#if LANG_CXX11
void StbInspectData::set_entityinstance(::std::string&& value) {
  
  entityinstance_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.entityInstance)
}
#endif
void StbInspectData::set_entityinstance(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  entityinstance_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.entityInstance)
}
void StbInspectData::set_entityinstance(const char* value, size_t size) {
  
  entityinstance_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.entityInstance)
}
::std::string* StbInspectData::mutable_entityinstance() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.entityInstance)
  return entityinstance_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_entityinstance() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.entityInstance)
  
  return entityinstance_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_entityinstance(::std::string* entityinstance) {
  if (entityinstance != NULL) {
    
  } else {
    
  }
  entityinstance_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), entityinstance);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.entityInstance)
}

// .proto.EnumDefineData.AppTypeEnum appTypeCode = 5;
void StbInspectData::clear_apptypecode() {
  apptypecode_ = 0;
}
::proto::EnumDefineData_AppTypeEnum StbInspectData::apptypecode() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.appTypeCode)
  return static_cast< ::proto::EnumDefineData_AppTypeEnum >(apptypecode_);
}
void StbInspectData::set_apptypecode(::proto::EnumDefineData_AppTypeEnum value) {
  
  apptypecode_ = value;
  // @@protoc_insertion_point(field_set:proto.StbInspectData.appTypeCode)
}

// string operDirect = 6;
void StbInspectData::clear_operdirect() {
  operdirect_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::operdirect() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.operDirect)
  return operdirect_.GetNoArena();
}
void StbInspectData::set_operdirect(const ::std::string& value) {
  
  operdirect_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.operDirect)
}
#if LANG_CXX11
void StbInspectData::set_operdirect(::std::string&& value) {
  
  operdirect_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.operDirect)
}
#endif
void StbInspectData::set_operdirect(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  operdirect_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.operDirect)
}
void StbInspectData::set_operdirect(const char* value, size_t size) {
  
  operdirect_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.operDirect)
}
::std::string* StbInspectData::mutable_operdirect() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.operDirect)
  return operdirect_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_operdirect() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.operDirect)
  
  return operdirect_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_operdirect(::std::string* operdirect) {
  if (operdirect != NULL) {
    
  } else {
    
  }
  operdirect_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operdirect);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.operDirect)
}

// string operName = 7;
void StbInspectData::clear_opername() {
  opername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::opername() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.operName)
  return opername_.GetNoArena();
}
void StbInspectData::set_opername(const ::std::string& value) {
  
  opername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.operName)
}
#if LANG_CXX11
void StbInspectData::set_opername(::std::string&& value) {
  
  opername_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.operName)
}
#endif
void StbInspectData::set_opername(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  opername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.operName)
}
void StbInspectData::set_opername(const char* value, size_t size) {
  
  opername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.operName)
}
::std::string* StbInspectData::mutable_opername() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.operName)
  return opername_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_opername() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.operName)
  
  return opername_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_opername(::std::string* opername) {
  if (opername != NULL) {
    
  } else {
    
  }
  opername_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), opername);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.operName)
}

// string operArgList = 8;
void StbInspectData::clear_operarglist() {
  operarglist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::operarglist() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.operArgList)
  return operarglist_.GetNoArena();
}
void StbInspectData::set_operarglist(const ::std::string& value) {
  
  operarglist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.operArgList)
}
#if LANG_CXX11
void StbInspectData::set_operarglist(::std::string&& value) {
  
  operarglist_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.operArgList)
}
#endif
void StbInspectData::set_operarglist(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  operarglist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.operArgList)
}
void StbInspectData::set_operarglist(const char* value, size_t size) {
  
  operarglist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.operArgList)
}
::std::string* StbInspectData::mutable_operarglist() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.operArgList)
  return operarglist_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_operarglist() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.operArgList)
  
  return operarglist_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_operarglist(::std::string* operarglist) {
  if (operarglist != NULL) {
    
  } else {
    
  }
  operarglist_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operarglist);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.operArgList)
}

// string operRst = 9;
void StbInspectData::clear_operrst() {
  operrst_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::operrst() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.operRst)
  return operrst_.GetNoArena();
}
void StbInspectData::set_operrst(const ::std::string& value) {
  
  operrst_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.operRst)
}
#if LANG_CXX11
void StbInspectData::set_operrst(::std::string&& value) {
  
  operrst_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.operRst)
}
#endif
void StbInspectData::set_operrst(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  operrst_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.operRst)
}
void StbInspectData::set_operrst(const char* value, size_t size) {
  
  operrst_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.operRst)
}
::std::string* StbInspectData::mutable_operrst() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.operRst)
  return operrst_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_operrst() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.operRst)
  
  return operrst_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_operrst(::std::string* operrst) {
  if (operrst != NULL) {
    
  } else {
    
  }
  operrst_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operrst);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.operRst)
}

// string operOccurTime = 10;
void StbInspectData::clear_operoccurtime() {
  operoccurtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::operoccurtime() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.operOccurTime)
  return operoccurtime_.GetNoArena();
}
void StbInspectData::set_operoccurtime(const ::std::string& value) {
  
  operoccurtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.operOccurTime)
}
#if LANG_CXX11
void StbInspectData::set_operoccurtime(::std::string&& value) {
  
  operoccurtime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.operOccurTime)
}
#endif
void StbInspectData::set_operoccurtime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  operoccurtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.operOccurTime)
}
void StbInspectData::set_operoccurtime(const char* value, size_t size) {
  
  operoccurtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.operOccurTime)
}
::std::string* StbInspectData::mutable_operoccurtime() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.operOccurTime)
  return operoccurtime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_operoccurtime() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.operOccurTime)
  
  return operoccurtime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_operoccurtime(::std::string* operoccurtime) {
  if (operoccurtime != NULL) {
    
  } else {
    
  }
  operoccurtime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operoccurtime);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.operOccurTime)
}

// string desp = 11;
void StbInspectData::clear_desp() {
  desp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StbInspectData::desp() const {
  // @@protoc_insertion_point(field_get:proto.StbInspectData.desp)
  return desp_.GetNoArena();
}
void StbInspectData::set_desp(const ::std::string& value) {
  
  desp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.StbInspectData.desp)
}
#if LANG_CXX11
void StbInspectData::set_desp(::std::string&& value) {
  
  desp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.StbInspectData.desp)
}
#endif
void StbInspectData::set_desp(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  desp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.StbInspectData.desp)
}
void StbInspectData::set_desp(const char* value, size_t size) {
  
  desp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.StbInspectData.desp)
}
::std::string* StbInspectData::mutable_desp() {
  
  // @@protoc_insertion_point(field_mutable:proto.StbInspectData.desp)
  return desp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StbInspectData::release_desp() {
  // @@protoc_insertion_point(field_release:proto.StbInspectData.desp)
  
  return desp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StbInspectData::set_allocated_desp(::std::string* desp) {
  if (desp != NULL) {
    
  } else {
    
  }
  desp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), desp);
  // @@protoc_insertion_point(field_set_allocated:proto.StbInspectData.desp)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)
