##c/c++代码编译Makefile
###########################################################

all: 
	$(MAKE) -C src
	@echo "============make end==========================="
pkg:
	@echo "to pkg"

clean:
	$(MAKE) clean -C src

install:
	$(MAKE)


